import asyncio

from sqlalchemy import select

from app.config.database import AsyncSessionLocal
from app.models.question import Question, QuestionOption
from app.models.topic import Topic


QUESTIONS = [
    # QUIZ QUESTIONS
    {
        "question_text": "Що таке GIL у Python?",
        "answer_text": "GIL — це Global Interpreter Lock.",
        "explanation": "GIL дозволяє лише одному потоку виконувати Python bytecode одночасно у CPython.",
        "difficulty": "medium",
        "question_type": "single_choice",
        "options": [
            ("Global Interpreter Lock", True),
            ("General Import Logic", False),
            ("Global Interface Layer", False),
            ("Git Integration Logic", False),
        ],
    },
    {
        "question_text": "Яке ключове слово використовується для створення функції?",
        "answer_text": "def",
        "explanation": "У Python функції створюються через ключове слово def.",
        "difficulty": "easy",
        "question_type": "single_choice",
        "options": [
            ("function", False),
            ("func", False),
            ("def", True),
            ("lambda", False),
        ],
    },
    {
        "question_text": "Що повертає range() у Python 3?",
        "answer_text": "range object",
        "explanation": "range() у Python 3 повертає lazy range object.",
        "difficulty": "easy",
        "question_type": "single_choice",
        "options": [
            ("list", False),
            ("tuple", False),
            ("range object", True),
            ("generator", False),
        ],
    },
    {
        "question_text": "Яка структура даних є immutable?",
        "answer_text": "tuple",
        "explanation": "Tuple не можна змінити після створення.",
        "difficulty": "easy",
        "question_type": "single_choice",
        "options": [
            ("list", False),
            ("dict", False),
            ("set", False),
            ("tuple", True),
        ],
    },
    {
        "question_text": "Що робить append() у list?",
        "answer_text": "Додає елемент у кінець списку.",
        "explanation": "append() змінює список на місці.",
        "difficulty": "easy",
        "question_type": "single_choice",
        "options": [
            ("Додає елемент у кінець", True),
            ("Видаляє елемент", False),
            ("Сортує список", False),
            ("Створює копію", False),
        ],
    },
    {
        "question_text": "Що таке self у методі класу?",
        "answer_text": "Посилання на поточний екземпляр класу.",
        "explanation": "Через self можна звертатись до атрибутів об'єкта.",
        "difficulty": "easy",
        "question_type": "single_choice",
        "options": [
            ("Поточний екземпляр класу", True),
            ("Батьківський клас", False),
            ("Глобальна змінна", False),
            ("Тип даних", False),
        ],
    },
    {
        "question_text": "Який exception виникає при зверненні до неіснуючого ключа dict?",
        "answer_text": "KeyError",
        "explanation": "dict[key] викликає KeyError, якщо ключ не існує.",
        "difficulty": "easy",
        "question_type": "single_choice",
        "options": [
            ("IndexError", False),
            ("TypeError", False),
            ("KeyError", True),
            ("ValueError", False),
        ],
    },
    {
        "question_text": "Що поверне bool([])?",
        "answer_text": "False",
        "explanation": "Порожні колекції у Python є falsy.",
        "difficulty": "easy",
        "question_type": "single_choice",
        "options": [
            ("True", False),
            ("False", True),
            ("None", False),
            ("Помилку", False),
        ],
    },
    {
        "question_text": "Для чого використовується try/except?",
        "answer_text": "Для обробки винятків.",
        "explanation": "try/except дозволяє обробляти помилки без падіння програми.",
        "difficulty": "easy",
        "question_type": "single_choice",
        "options": [
            ("Для циклів", False),
            ("Для обробки помилок", True),
            ("Для створення функцій", False),
            ("Для імпорту модулів", False),
        ],
    },
    {
        "question_text": "Що створює list comprehension?",
        "answer_text": "Новий список.",
        "explanation": "List comprehension — короткий синтаксис створення списків.",
        "difficulty": "easy",
        "question_type": "single_choice",
        "options": [
            ("Новий dict", False),
            ("Новий set", False),
            ("Новий список", True),
            ("Generator", False),
        ],
    },
    {
        "question_text": "Що означає HTTP статус 404?",
        "answer_text": "Not Found",
        "explanation": "Сервер не знайшов ресурс.",
        "difficulty": "easy",
        "question_type": "single_choice",
        "options": [
            ("Unauthorized", False),
            ("Forbidden", False),
            ("Not Found", True),
            ("Internal Server Error", False),
        ],
    },
    {
        "question_text": "Що означає HTTP статус 401?",
        "answer_text": "Unauthorized",
        "explanation": "Користувач не авторизований.",
        "difficulty": "easy",
        "question_type": "single_choice",
        "options": [
            ("Unauthorized", True),
            ("Forbidden", False),
            ("Conflict", False),
            ("Bad Request", False),
        ],
    },
    {
        "question_text": "Який HTTP метод зазвичай використовують для створення ресурсу?",
        "answer_text": "POST",
        "explanation": "POST використовується для створення нових ресурсів.",
        "difficulty": "easy",
        "question_type": "single_choice",
        "options": [
            ("GET", False),
            ("POST", True),
            ("DELETE", False),
            ("PATCH", False),
        ],
    },
    {
        "question_text": "Що таке JWT?",
        "answer_text": "JSON Web Token",
        "explanation": "JWT часто використовують для авторизації.",
        "difficulty": "medium",
        "question_type": "single_choice",
        "options": [
            ("Java Web Token", False),
            ("JSON Web Token", True),
            ("Joined Web Template", False),
            ("JSON Worker Token", False),
        ],
    },
    {
        "question_text": "Як правильно зберігати пароль у БД?",
        "answer_text": "У вигляді хешу.",
        "explanation": "Паролі не можна зберігати у відкритому вигляді.",
        "difficulty": "easy",
        "question_type": "single_choice",
        "options": [
            ("Plain text", False),
            ("Base64", False),
            ("У вигляді хешу", True),
            ("JWT", False),
        ],
    },
    {
        "question_text": "Що таке SQL JOIN?",
        "answer_text": "Операція об'єднання таблиць.",
        "explanation": "JOIN дозволяє отримувати дані з кількох таблиць.",
        "difficulty": "medium",
        "question_type": "single_choice",
        "options": [
            ("Об'єднання таблиць", True),
            ("Створення таблиці", False),
            ("Видалення таблиці", False),
            ("Сортування таблиці", False),
        ],
    },
    {
        "question_text": "Для чого потрібен індекс у БД?",
        "answer_text": "Для пришвидшення пошуку.",
        "explanation": "Індекси прискорюють SELECT-запити.",
        "difficulty": "medium",
        "question_type": "single_choice",
        "options": [
            ("Для кешування", False),
            ("Для пришвидшення пошуку", True),
            ("Для Docker", False),
            ("Для JWT", False),
        ],
    },
    {
        "question_text": "Що таке primary key?",
        "answer_text": "Унікальний ідентифікатор рядка.",
        "explanation": "Primary key однозначно ідентифікує запис.",
        "difficulty": "easy",
        "question_type": "single_choice",
        "options": [
            ("Foreign key", False),
            ("Unique identifier", True),
            ("Index", False),
            ("Constraint", False),
        ],
    },
    {
        "question_text": "Що таке foreign key?",
        "answer_text": "Посилання на запис іншої таблиці.",
        "explanation": "Foreign key використовується для зв'язків між таблицями.",
        "difficulty": "easy",
        "question_type": "single_choice",
        "options": [
            ("Primary key", False),
            ("Посилання на іншу таблицю", True),
            ("Index", False),
            ("JSON field", False),
        ],
    },
    {
        "question_text": "Що таке Docker image?",
        "answer_text": "Шаблон для створення контейнера.",
        "explanation": "Image містить застосунок та його залежності.",
        "difficulty": "easy",
        "question_type": "single_choice",
        "options": [
            ("Запущений процес", False),
            ("Шаблон контейнера", True),
            ("База даних", False),
            ("Git branch", False),
        ],
    },
    {
        "question_text": "Що таке Docker container?",
        "answer_text": "Запущений екземпляр image.",
        "explanation": "Container створюється на основі image.",
        "difficulty": "easy",
        "question_type": "single_choice",
        "options": [
            ("Запущений image", True),
            ("Git repository", False),
            ("SQL table", False),
            ("Python module", False),
        ],
    },
    {
        "question_text": "Для чого потрібен docker-compose?",
        "answer_text": "Для запуску кількох сервісів разом.",
        "explanation": "Compose дозволяє описувати кілька контейнерів у одному файлі.",
        "difficulty": "easy",
        "question_type": "single_choice",
        "options": [
            ("Для запуску кількох сервісів", True),
            ("Для тестів", False),
            ("Для JWT", False),
            ("Для SQL", False),
        ],
    },
    {
        "question_text": "Що таке ORM?",
        "answer_text": "Object Relational Mapping",
        "explanation": "ORM дозволяє працювати з БД через Python-класи.",
        "difficulty": "medium",
        "question_type": "single_choice",
        "options": [
            ("Open Runtime Module", False),
            ("Object Relational Mapping", True),
            ("Online Request Method", False),
            ("Object Render Manager", False),
        ],
    },
    {
        "question_text": "Для чого потрібен Alembic?",
        "answer_text": "Для міграцій бази даних.",
        "explanation": "Alembic дозволяє керувати змінами схеми БД.",
        "difficulty": "medium",
        "question_type": "single_choice",
        "options": [
            ("Для тестів", False),
            ("Для Docker", False),
            ("Для міграцій БД", True),
            ("Для JWT", False),
        ],
    },
    {
        "question_text": "Що таке async/await?",
        "answer_text": "Синтаксис асинхронного програмування.",
        "explanation": "async/await використовується для неблокуючих операцій.",
        "difficulty": "medium",
        "question_type": "single_choice",
        "options": [
            ("Механізм багатопоточності", False),
            ("Асинхронний синтаксис", True),
            ("SQL синтаксис", False),
            ("Docker feature", False),
        ],
    },
    {
        "question_text": "Для чого використовується pytest?",
        "answer_text": "Для тестування Python-коду.",
        "explanation": "pytest — популярний Python testing framework.",
        "difficulty": "easy",
        "question_type": "single_choice",
        "options": [
            ("Для тестування", True),
            ("Для Docker", False),
            ("Для SQL", False),
            ("Для React", False),
        ],
    },
    {
        "question_text": "Що таке dependency injection у FastAPI?",
        "answer_text": "Механізм Depends.",
        "explanation": "Depends дозволяє передавати залежності у route handlers.",
        "difficulty": "medium",
        "question_type": "single_choice",
        "options": [
            ("Depends", True),
            ("Middleware", False),
            ("Migration", False),
            ("Decorator", False),
        ],
    },
    {
        "question_text": "Що таке CORS?",
        "answer_text": "Механізм контролю доступу між origins.",
        "explanation": "CORS дозволяє frontend робити запити до іншого origin.",
        "difficulty": "medium",
        "question_type": "single_choice",
        "options": [
            ("Cross-Origin Resource Sharing", True),
            ("Container Object Runtime Service", False),
            ("Cross Object Render System", False),
            ("Cache Object Routing Service", False),
        ],
    },
    {
        "question_text": "Що робить оператор pass?",
        "answer_text": "Нічого.",
        "explanation": "pass — це заглушка для порожнього блоку коду.",
        "difficulty": "easy",
        "question_type": "single_choice",
        "options": [
            ("Пропускає ітерацію", False),
            ("Нічого не робить", True),
            ("Завершує цикл", False),
            ("Створює exception", False),
        ],
    },
    {
        "question_text": "Який тип даних використовується для key-value пар?",
        "answer_text": "dict",
        "explanation": "dict зберігає дані у форматі key-value.",
        "difficulty": "easy",
        "question_type": "single_choice",
        "options": [
            ("tuple", False),
            ("dict", True),
            ("set", False),
            ("list", False),
        ],
    },
    {
        "question_text": "Що повертає dict.keys()?",
        "answer_text": "Колекцію ключів.",
        "explanation": "dict.keys() повертає view object.",
        "difficulty": "easy",
        "question_type": "single_choice",
        "options": [
            ("Колекцію ключів", True),
            ("Колекцію значень", False),
            ("Tuple", False),
            ("Generator", False),
        ],
    },
    {
        "question_text": "Який цикл використовується для ітерації по iterable?",
        "answer_text": "for",
        "explanation": "for використовується для проходження по iterable об'єктах.",
        "difficulty": "easy",
        "question_type": "single_choice",
        "options": [
            ("while", False),
            ("foreach", False),
            ("for", True),
            ("iterate", False),
        ],
    },
    {
        "question_text": "Що робить break у циклі?",
        "answer_text": "Завершує цикл.",
        "explanation": "break виходить із поточного циклу.",
        "difficulty": "easy",
        "question_type": "single_choice",
        "options": [
            ("Пропускає ітерацію", False),
            ("Перезапускає цикл", False),
            ("Завершує цикл", True),
            ("Ігнорує помилку", False),
        ],
    },
    {
        "question_text": "Що таке virtual environment?",
        "answer_text": "Ізольоване середовище Python.",
        "explanation": "venv дозволяє мати окремі залежності для проектів.",
        "difficulty": "easy",
        "question_type": "single_choice",
        "options": [
            ("Docker image", False),
            ("Ізольоване середовище", True),
            ("База даних", False),
            ("Git branch", False),
        ],
    },
    {
        "question_text": "Що робить pip?",
        "answer_text": "Встановлює Python-пакети.",
        "explanation": "pip — package manager Python.",
        "difficulty": "easy",
        "question_type": "single_choice",
        "options": [
            ("Запускає Python", False),
            ("Встановлює пакети", True),
            ("Компілює код", False),
            ("Створює Docker image", False),
        ],
    },
    {
        "question_text": "Що таке requirements.txt?",
        "answer_text": "Файл залежностей проекту.",
        "explanation": "requirements.txt містить список пакетів.",
        "difficulty": "easy",
        "question_type": "single_choice",
        "options": [
            ("Файл Docker", False),
            ("Файл залежностей", True),
            ("SQL schema", False),
            ("JWT config", False),
        ],
    },
    {
        "question_text": "Що таке middleware у FastAPI?",
        "answer_text": "Компонент для обробки request/response.",
        "explanation": "Middleware виконується до і після route handler.",
        "difficulty": "medium",
        "question_type": "single_choice",
        "options": [
            ("Decorator", False),
            ("Компонент request/response", True),
            ("ORM layer", False),
            ("SQL migration", False),
        ],
    },
    {
        "question_text": "Що таке hashing?",
        "answer_text": "Перетворення даних у фіксований рядок.",
        "explanation": "Hashing використовують для паролів.",
        "difficulty": "easy",
        "question_type": "single_choice",
        "options": [
            ("Encryption", False),
            ("Hashing", True),
            ("Compression", False),
            ("Serialization", False),
        ],
    },
    {
        "question_text": "Яка команда Git створює нову гілку?",
        "answer_text": "git checkout -b",
        "explanation": "checkout -b створює нову branch.",
        "difficulty": "easy",
        "question_type": "single_choice",
        "options": [
            ("git push", False),
            ("git checkout -b", True),
            ("git merge", False),
            ("git pull", False),
        ],
    },
    {
        "question_text": "Що робить git pull?",
        "answer_text": "Оновлює локальний репозиторій.",
        "explanation": "git pull = fetch + merge.",
        "difficulty": "easy",
        "question_type": "single_choice",
        "options": [
            ("Видаляє branch", False),
            ("Оновлює репозиторій", True),
            ("Створює commit", False),
            ("Запускає Docker", False),
        ],
    },
    {
        "question_text": "Що таке pagination?",
        "answer_text": "Розбиття даних на сторінки.",
        "explanation": "Pagination використовується для великих списків.",
        "difficulty": "easy",
        "question_type": "single_choice",
        "options": [
            ("Кешування", False),
            ("Pagination", True),
            ("JWT", False),
            ("Hashing", False),
        ],
    },
    {
        "question_text": "Що таке Redis?",
        "answer_text": "In-memory key-value database.",
        "explanation": "Redis часто використовують для кешу.",
        "difficulty": "medium",
        "question_type": "single_choice",
        "options": [
            ("Frontend framework", False),
            ("In-memory database", True),
            ("ORM", False),
            ("Web server", False),
        ],
    },
    {
        "question_text": "Що таке Celery?",
        "answer_text": "Task queue для background jobs.",
        "explanation": "Celery виконує асинхронні задачі.",
        "difficulty": "medium",
        "question_type": "single_choice",
        "options": [
            ("ORM", False),
            ("Task queue", True),
            ("Database", False),
            ("Docker service", False),
        ],
    },
    {
        "question_text": "Що таке Kafka?",
        "answer_text": "Message broker.",
        "explanation": "Kafka використовується для потокової обробки повідомлень.",
        "difficulty": "hard",
        "question_type": "single_choice",
        "options": [
            ("ORM", False),
            ("Message broker", True),
            ("SQL engine", False),
            ("HTTP framework", False),
        ],
    },
    {
        "question_text": "Який HTTP метод використовується для видалення ресурсу?",
        "answer_text": "DELETE",
        "explanation": "DELETE видаляє ресурс.",
        "difficulty": "easy",
        "question_type": "single_choice",
        "options": [
            ("GET", False),
            ("PATCH", False),
            ("DELETE", True),
            ("POST", False),
        ],
    },
    {
        "question_text": "Що таке PATCH request?",
        "answer_text": "Часткове оновлення ресурсу.",
        "explanation": "PATCH оновлює лише частину полів.",
        "difficulty": "medium",
        "question_type": "single_choice",
        "options": [
            ("Повна заміна", False),
            ("Часткове оновлення", True),
            ("Видалення", False),
            ("Створення", False),
        ],
    },
    {
        "question_text": "Що таке unit test?",
        "answer_text": "Тест окремої частини логіки.",
        "explanation": "Unit tests перевіряють ізольовану логіку.",
        "difficulty": "easy",
        "question_type": "single_choice",
        "options": [
            ("Тест UI", False),
            ("Тест логіки", True),
            ("Тест Docker", False),
            ("Тест CSS", False),
        ],
    },
    {
        "question_text": "Що таке integration test?",
        "answer_text": "Тест взаємодії компонентів.",
        "explanation": "Integration tests перевіряють роботу системи разом.",
        "difficulty": "medium",
        "question_type": "single_choice",
        "options": [
            ("Тест CSS", False),
            ("Тест Docker", False),
            ("Тест взаємодії компонентів", True),
            ("Тест Git", False),
        ],
    },

    # FLASHCARDS
    {
    "question_text": "Що таке декоратор у Python?",
    "answer_text": "Декоратор — це функція, яка змінює поведінку іншої функції або класу.",
    "explanation": "Декоратори часто використовують для логування, авторизації, кешування та перевірок.",
    "difficulty": "medium",
    "question_type": "flashcard",
    "options": [],
    },
    {
        "question_text": "У чому різниця між list і tuple?",
        "answer_text": "list є mutable, а tuple immutable.",
        "explanation": "list можна змінювати після створення, tuple — ні.",
        "difficulty": "easy",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке генератор у Python?",
        "answer_text": "Генератор — це ітератор, який повертає значення через yield.",
        "explanation": "Генератори дозволяють економити пам'ять.",
        "difficulty": "medium",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке context manager?",
        "answer_text": "Механізм для автоматичного setup/cleanup ресурсів.",
        "explanation": "Найчастіше використовується через with.",
        "difficulty": "medium",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "У чому різниця між == та is?",
        "answer_text": "== порівнює значення, а is — ідентичність об'єктів.",
        "explanation": "is перевіряє, чи це той самий об'єкт у пам'яті.",
        "difficulty": "easy",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке duck typing?",
        "answer_text": "Підхід, де важлива поведінка об'єкта, а не його тип.",
        "explanation": "Якщо об'єкт має потрібні методи — його можна використовувати.",
        "difficulty": "medium",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке shallow copy?",
        "answer_text": "Поверхнева копія об'єкта.",
        "explanation": "Вкладені об'єкти залишаються спільними.",
        "difficulty": "medium",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке deep copy?",
        "answer_text": "Повна рекурсивна копія об'єкта.",
        "explanation": "Вкладені об'єкти теж копіюються.",
        "difficulty": "medium",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке PEP 8?",
        "answer_text": "Style guide для Python.",
        "explanation": "PEP 8 описує стандарти написання Python-коду.",
        "difficulty": "easy",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке mutable об'єкт?",
        "answer_text": "Об'єкт, який можна змінювати після створення.",
        "explanation": "Наприклад list або dict.",
        "difficulty": "easy",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке immutable об'єкт?",
        "answer_text": "Об'єкт, який не можна змінити після створення.",
        "explanation": "Наприклад tuple або str.",
        "difficulty": "easy",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке FastAPI?",
        "answer_text": "Сучасний Python framework для створення API.",
        "explanation": "FastAPI підтримує async, dependency injection і OpenAPI.",
        "difficulty": "easy",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке Pydantic?",
        "answer_text": "Бібліотека для валідації даних.",
        "explanation": "Pydantic активно використовується у FastAPI.",
        "difficulty": "easy",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке SQLAlchemy?",
        "answer_text": "ORM для Python.",
        "explanation": "SQLAlchemy дозволяє працювати з БД через Python-класи.",
        "difficulty": "medium",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке N+1 проблема?",
        "answer_text": "Проблема великої кількості SQL-запитів.",
        "explanation": "Виникає при неефективному завантаженні зв'язків.",
        "difficulty": "medium",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке repository pattern?",
        "answer_text": "Патерн для ізоляції роботи з БД.",
        "explanation": "Repository відділяє бізнес-логіку від SQL.",
        "difficulty": "medium",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке service layer?",
        "answer_text": "Шар бізнес-логіки застосунку.",
        "explanation": "Service layer не дає писати бізнес-логіку в роутерах.",
        "difficulty": "medium",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке REST API?",
        "answer_text": "Архітектурний стиль для API.",
        "explanation": "REST використовує HTTP методи та ресурси.",
        "difficulty": "easy",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке idempotency?",
        "answer_text": "Повторний запит дає той самий результат.",
        "explanation": "GET і PUT зазвичай idempotent.",
        "difficulty": "medium",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке database transaction?",
        "answer_text": "Група операцій, які виконуються як одне ціле.",
        "explanation": "Транзакція або повністю проходить, або відкатується.",
        "difficulty": "medium",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке ACID?",
        "answer_text": "Набір властивостей транзакцій.",
        "explanation": "Atomicity, Consistency, Isolation, Durability.",
        "difficulty": "medium",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке Docker volume?",
        "answer_text": "Механізм збереження даних Docker.",
        "explanation": "Volumes дозволяють зберігати дані між перезапусками контейнера.",
        "difficulty": "easy",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке SOLID?",
        "answer_text": "5 принципів ООП-дизайну.",
        "explanation": "SOLID покращує підтримуваність та масштабованість коду.",
        "difficulty": "medium",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке singleton pattern?",
        "answer_text": "Патерн з одним екземпляром класу.",
        "explanation": "Singleton часто використовують для logger або config.",
        "difficulty": "medium",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке dependency injection?",
        "answer_text": "Передача залежностей ззовні.",
        "explanation": "Dependency injection покращує тестованість.",
        "difficulty": "medium",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке caching?",
        "answer_text": "Тимчасове збереження даних для швидкого доступу.",
        "explanation": "Кеш зменшує навантаження на систему.",
        "difficulty": "easy",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке rate limiting?",
        "answer_text": "Обмеження кількості запитів.",
        "explanation": "Rate limiting захищає API від перевантаження.",
        "difficulty": "medium",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке WebSocket?",
        "answer_text": "Протокол для realtime-з'єднання.",
        "explanation": "WebSocket дозволяє двосторонній зв'язок між клієнтом і сервером.",
        "difficulty": "medium",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке environment variables?",
        "answer_text": "Змінні середовища для конфігурації.",
        "explanation": "Часто використовуються для секретів і URL.",
        "difficulty": "easy",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке CI/CD?",
        "answer_text": "Автоматизація тестування та деплою.",
        "explanation": "CI — Continuous Integration, CD — Continuous Deployment.",
        "difficulty": "medium",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке reverse proxy?",
        "answer_text": "Сервер-посередник між клієнтом і backend.",
        "explanation": "Nginx часто використовується як reverse proxy.",
        "difficulty": "medium",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке Nginx?",
        "answer_text": "Вебсервер і reverse proxy.",
        "explanation": "Nginx часто ставлять перед FastAPI backend.",
        "difficulty": "easy",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке load balancing?",
        "answer_text": "Розподіл навантаження між серверами.",
        "explanation": "Load balancing допомагає масштабувати систему.",
        "difficulty": "medium",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке horizontal scaling?",
        "answer_text": "Додавання нових серверів.",
        "explanation": "Horizontal scaling збільшує кількість інстансів.",
        "difficulty": "medium",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке vertical scaling?",
        "answer_text": "Збільшення ресурсів сервера.",
        "explanation": "Наприклад більше RAM або CPU.",
        "difficulty": "medium",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке race condition?",
        "answer_text": "Помилка через одночасний доступ до даних.",
        "explanation": "Race condition часто виникає в multithreading.",
        "difficulty": "hard",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке deadlock?",
        "answer_text": "Взаємне блокування процесів.",
        "explanation": "Процеси чекають один одного нескінченно.",
        "difficulty": "hard",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке serialization?",
        "answer_text": "Перетворення об'єкта у формат передачі.",
        "explanation": "Наприклад object → JSON.",
        "difficulty": "easy",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке deserialization?",
        "answer_text": "Перетворення даних назад у об'єкт.",
        "explanation": "Наприклад JSON → Python object.",
        "difficulty": "easy",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке bearer token?",
        "answer_text": "Токен авторизації у header.",
        "explanation": "Bearer token часто використовується з JWT.",
        "difficulty": "easy",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке HTTPS?",
        "answer_text": "Захищена версія HTTP.",
        "explanation": "HTTPS шифрує трафік через TLS.",
        "difficulty": "easy",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке monkeypatch у pytest?",
        "answer_text": "Механізм підміни об'єктів під час тестів.",
        "explanation": "Monkeypatch дозволяє мокати функції та змінні.",
        "difficulty": "medium",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке mock?",
        "answer_text": "Фейковий об'єкт для тестування.",
        "explanation": "Mocks дозволяють ізолювати логіку.",
        "difficulty": "medium",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке async task?",
        "answer_text": "Задача, яка виконується неблокуюче.",
        "explanation": "Async tasks дозволяють ефективно працювати з I/O.",
        "difficulty": "medium",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке event loop?",
        "answer_text": "Механізм виконання async задач.",
        "explanation": "Event loop керує coroutine у asyncio.",
        "difficulty": "hard",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке coroutine?",
        "answer_text": "Асинхронна функція.",
        "explanation": "Coroutine створюється через async def.",
        "difficulty": "medium",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке JSON?",
        "answer_text": "Формат обміну даними.",
        "explanation": "JSON часто використовується в REST API.",
        "difficulty": "easy",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке API?",
        "answer_text": "Інтерфейс взаємодії між системами.",
        "explanation": "API дозволяє різним сервісам обмінюватися даними.",
        "difficulty": "easy",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке microservices?",
        "answer_text": "Архітектура з незалежних сервісів.",
        "explanation": "Кожен сервіс виконує окрему задачу.",
        "difficulty": "medium",
        "question_type": "flashcard",
        "options": [],
    },
    {
        "question_text": "Що таке monolith?",
        "answer_text": "Єдиний великий застосунок.",
        "explanation": "Усі компоненти працюють в одному проекті.",
        "difficulty": "easy",
        "question_type": "flashcard",
        "options": [],
    },
]


async def seed():
    async with AsyncSessionLocal() as session:
        existing_topic = await session.execute(
            select(Topic).where(Topic.slug == "python")
        )

        if existing_topic.scalar_one_or_none():
            print("Seed already exists")
            return

        python_topic = Topic(
            title="Python",
            slug="python",
            description="Python interview questions",
        )

        session.add(python_topic)
        await session.flush()

        for question_data in QUESTIONS:
            question = Question(
                topic_id=python_topic.id,
                question_text=question_data["question_text"],
                answer_text=question_data["answer_text"],
                explanation=question_data["explanation"],
                difficulty=question_data["difficulty"],
                question_type=question_data["question_type"],
            )

            session.add(question)
            await session.flush()

            if question_data["options"]:
                options = [
                    QuestionOption(
                        question_id=question.id,
                        option_text=option_text,
                        is_correct=is_correct,
                    )
                    for option_text, is_correct in question_data["options"]
                ]

                session.add_all(options)

        await session.commit()

        print("Seed completed")


if __name__ == "__main__":
    asyncio.run(seed())