"""add user question progress

Revision ID: b3ab8f783077
Revises: 7980ff9af9bf
Create Date: 2026-05-17 21:33:23.324862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3ab8f783077'
down_revision: Union[str, Sequence[str], None] = '7980ff9af9bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_question_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('attempts_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('wrong_count', sa.Integer(), nullable=False),
    sa.Column('flashcard_status', sa.String(length=30), nullable=True),
    sa.Column('last_answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question_id', name='uq_user_question_progress')
    )
    op.create_index(op.f('ix_user_question_progress_question_id'), 'user_question_progress', ['question_id'], unique=False)
    op.create_index(op.f('ix_user_question_progress_user_id'), 'user_question_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_question_progress_user_id'), table_name='user_question_progress')
    op.drop_index(op.f('ix_user_question_progress_question_id'), table_name='user_question_progress')
    op.drop_table('user_question_progress')
    # ### end Alembic commands ###
